# These are supported funding model platforms

github: [Al-homaidi]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective name
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ['https://portfolio-mohammed-mahfouzs-projects.vercel.app/', 'https://www.linkedin.com/in/mohammed-mahfouz-al-homaidi-1876b631b/']
